/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import '@stencil/router';

import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';

declare global {

  namespace StencilComponents {
    interface BlogEntry {

    }
  }

  interface HTMLBlogEntryElement extends StencilComponents.BlogEntry, HTMLStencilElement {}

  var HTMLBlogEntryElement: {
    prototype: HTMLBlogEntryElement;
    new (): HTMLBlogEntryElement;
  };
  interface HTMLElementTagNameMap {
    'blog-entry': HTMLBlogEntryElement;
  }
  interface ElementTagNameMap {
    'blog-entry': HTMLBlogEntryElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'blog-entry': JSXElements.BlogEntryAttributes;
    }
  }
  namespace JSXElements {
    export interface BlogEntryAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface BlogPage {
      'match': MatchResults;
    }
  }

  interface HTMLBlogPageElement extends StencilComponents.BlogPage, HTMLStencilElement {}

  var HTMLBlogPageElement: {
    prototype: HTMLBlogPageElement;
    new (): HTMLBlogPageElement;
  };
  interface HTMLElementTagNameMap {
    'blog-page': HTMLBlogPageElement;
  }
  interface ElementTagNameMap {
    'blog-page': HTMLBlogPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'blog-page': JSXElements.BlogPageAttributes;
    }
  }
  namespace JSXElements {
    export interface BlogPageAttributes extends HTMLAttributes {
      'match'?: MatchResults;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface MyApp {

    }
  }

  interface HTMLMyAppElement extends StencilComponents.MyApp, HTMLStencilElement {}

  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };
  interface HTMLElementTagNameMap {
    'my-app': HTMLMyAppElement;
  }
  interface ElementTagNameMap {
    'my-app': HTMLMyAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'my-app': JSXElements.MyAppAttributes;
    }
  }
  namespace JSXElements {
    export interface MyAppAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface TableOfContents {
      'history': RouterHistory;
    }
  }

  interface HTMLTableOfContentsElement extends StencilComponents.TableOfContents, HTMLStencilElement {}

  var HTMLTableOfContentsElement: {
    prototype: HTMLTableOfContentsElement;
    new (): HTMLTableOfContentsElement;
  };
  interface HTMLElementTagNameMap {
    'table-of-contents': HTMLTableOfContentsElement;
  }
  interface ElementTagNameMap {
    'table-of-contents': HTMLTableOfContentsElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'table-of-contents': JSXElements.TableOfContentsAttributes;
    }
  }
  namespace JSXElements {
    export interface TableOfContentsAttributes extends HTMLAttributes {
      'history'?: RouterHistory;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
